// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyVFY6qGIu5cViy_Mduh4nHjn9kk8ItmY',
    appId: '1:824368180402:web:29142e724459cb0a6c2dab',
    messagingSenderId: '824368180402',
    projectId: 'flickreview-4451b',
    authDomain: 'flickreview-4451b.firebaseapp.com',
    storageBucket: 'flickreview-4451b.firebasestorage.app',
    measurementId: 'G-MDJN5JY3M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9VxmPapwLF3fc4Lme0O-e-X2_TY8LAXU',
    appId: '1:824368180402:android:cad7727420a0cbf06c2dab',
    messagingSenderId: '824368180402',
    projectId: 'flickreview-4451b',
    storageBucket: 'flickreview-4451b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXNwKlcUSbddFZ6LYUgOkiAexLCdxCLc',
    appId: '1:824368180402:ios:76697ea6dced776d6c2dab',
    messagingSenderId: '824368180402',
    projectId: 'flickreview-4451b',
    storageBucket: 'flickreview-4451b.firebasestorage.app',
    iosBundleId: 'com.example.flickreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXNwKlcUSbddFZ6LYUgOkiAexLCdxCLc',
    appId: '1:824368180402:ios:76697ea6dced776d6c2dab',
    messagingSenderId: '824368180402',
    projectId: 'flickreview-4451b',
    storageBucket: 'flickreview-4451b.firebasestorage.app',
    iosBundleId: 'com.example.flickreview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyVFY6qGIu5cViy_Mduh4nHjn9kk8ItmY',
    appId: '1:824368180402:web:5dcae162424073906c2dab',
    messagingSenderId: '824368180402',
    projectId: 'flickreview-4451b',
    authDomain: 'flickreview-4451b.firebaseapp.com',
    storageBucket: 'flickreview-4451b.firebasestorage.app',
    measurementId: 'G-LZW02HP7ZG',
  );
}
